version: '3'

services:
  test_db:
    image: postgres:15.1-alpine
    restart: always
    container_name: test_db
    volumes:
      - test_postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - .env_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_web:
    build: .
    container_name: test_web
    command: sh -c "pytest -v"
    volumes:
      - .:/app
      - .:/tests
    ports:
      - 8009:8000
    env_file:
      - .env_test
    depends_on:
      test_db:
        condition: service_healthy

volumes:
  test_postgres_data:
