version: '3'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8080:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://menu_db_admin:menu_db_admin@db:5432/menu_db
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      POSTGRES_DB: menu_db
      POSTGRES_USER: menu_db_admin
      POSTGRES_PASSWORD: menu_db_admin

volumes:
  postgres_data: