version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env_compose
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env_compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: