version: '3'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: menu_db
      POSTGRES_USER: menu_db_admin
      POSTGRES_PASSWORD: menu_db_admin

volumes:
  postgres_test_data: