version: '3'

services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: menu_db
      POSTGRES_USER: menu_db_admin
      POSTGRES_PASSWORD: menu_db_admin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: