version: '3'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_local_test_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "15432:5432"
    env_file: local.env

volumes:
  postgres_local_test_data: