version: '3'

services:
  db:
    image: postgres:15.1-alpine
    networks:
      - ylab_menu_network
    volumes:
      - postgres_local_test_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "15432:5432"
    env_file: .env

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - ylab_menu_network
    volumes:
      - redis_local_test_data:/data
    expose:
      - 6379
    ports:
      - "16379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    restart: always
    container_name: rabbitmq
    networks:
      - ylab_menu_network
    volumes:
      - rabbit_local_test_data:/var/lib/rabbitmq
    env_file:
      - .env
    ports:
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 5

  # celery:
    # build:
      # context: .
      # dockerfile: Dockerfile
    # networks:
      # - ylab_menu_network
    # env_file:
      # - .env
    # container_name: celery
    # restart: always
    # command: ["celery", "--app=app.celery.tasks:app", "worker", "-l", "INFO"]
    # depends_on:
      # - db
      # - redis
      # - rabbitmq

networks:
  ylab_menu_network:
    name: ylab_menu_network
volumes:
  postgres_local_test_data:
    name: postgres_local_test_data
  redis_local_test_data:
    name: redis_local_test_data
  rabbit_local_test_data:
    name: rabbit_local_test_data
