from sqlalchemy import DECIMAL, Column, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, relationship

from app.config.database import Base
from app.utils.generators import generate_uuid


class Dish(Base):
    """
    SQLAlchemy model for `dishes` table in database\n
    ## Attributes:
        id -> (autogenerated) `str`\n
        title -> `str`\n
        description -> `str`\n
        price -> `Decimal`\n
        discount -> `Integer`\n
        submenu_id -> FK to 'submenus' through `submenus.id`\n
        submenu related to SubMenu model backpopulates dishes
    """
    __tablename__ = 'dishes'

    id = Column(
        String,
        primary_key=True,
        default=generate_uuid
    )
    title = Column(String)
    description = Column(String)
    price = Column(DECIMAL(precision=10, scale=2))
    discount = Column(Integer, default=0)

    submenu_id = Column(
        String,
        ForeignKey(
            'submenus.id',
            ondelete='CASCADE'
        )
    )
    submenu: Mapped['SubMenu'] = relationship(
        back_populates='dishes',
        # lazy='selectin'
    )
